version: "3.8"

services:
  db:
    image: postgres:16.1
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  api:
    build: ./api
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/rails
    ports:
      - 3000:3000
    depends_on:
      - db

  front:
    build: ./front
    environment:
      PORT: 4000
    command: npm run dev
    volumes:
      - ./front:/app
    ports:
      - 4000:4000
    depends_on:
      - api

volumes:
  data-volume: